### ISSUE TITLE
Mod Breaks Server

### ISSUE THREAD

**Issue by Volt-0001** [Christofmeg/FastEntityTransfer#8]
The mod made my server not being able to interact with any blocks. players could not in any way interact with blocks. open doors or chests, etc.

**Comment by Christofmeg** [comment]
@Volt-0001 What version did you use?

**Comment by Volt-0001** [comment]
sorry for not including. 1.18.2-1.1.2

**Comment by DadoIrie** [comment]
issue is still present - forge (43.2.3) 1.19.2
linked to the line where placed a block and block got removed next second with the error on console regarding `Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER`
[Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER](https://mclo.gs/z13o4nl#L10741)

**Comment by Christofmeg** [comment]
@dadoirie Based on the logs I can see that you're using fastentitytransfer-forge-1.19.x-1.1.2.jar,  which is not the newest version.
This issue was fixed for forge1.19.x in version 1.2.0
You can download the most recent versions on: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fastentitytransfer/files/4577542), [Modrinth](https://modrinth.com/mod/fastentitytransfer/version/uMz86mpL) and [Github](https://github.com/Christofmeg/FastEntityTransfer/releases/tag/forge-1.19.x-1.2.0)



> issue is still present - forge (43.2.3) 1.19.2 linked to the line where placed a block and block got removed next second with the error on console regarding `Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER` [Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER](https://mclo.gs/z13o4nl#L10741)

**Comment by DadoIrie** [comment]
ooh - my bad - thanks a lot

just got a bit confused here because the issue was reopened

**Comment by Christofmeg** [comment]
Now all versions for Forge 1.14-1.20 are fixed. Just need to do the same for Fabric
